Import('RTT_ROOT')
Import('rtconfig')
from building import * 

# get current dir path
cwd = GetCurrentDir()

# init src and inc vars
src = []
inc = []

# add dwin basic include
inc = inc + [cwd]

# add dwin basic code
src += ['board.c']
src += ['stm32f4xx_it.c']
src += ['drv_usart.c']
src += ['drv_romfs.c']

if GetDepend(['RT_USING_PIN']):
    src += ['drv_gpio.c']

if GetDepend(['BSP_USING_I2C2']):
	src += ['drv_i2c.c']

if GetDepend(['RT_USING_SPI']):
    src += ['drv_spi.c']

if GetDepend(['BSP_USING_SDRAM']):
    src += ['drv_sdram.c']

if GetDepend(['BSP_USING_SDCARD_BLOCK']):
    src += ['drv_sdcard.c']

if GetDepend(['BSP_USING_SDCARD_SDIO_BUS']):
    src += ['drv_sdio_adapter.c']

if GetDepend(['BSP_USING_LCD']):
    src += ['drv_lcd.c']

if GetDepend(['BSP_USING_AUDIO']):
    src += Glob('./audio/*.c')
    inc += [cwd + "/audio"] 

if GetDepend(['BSP_USING_RAMDISK']):
    src += ['drv_ramdisk.c']

if GetDepend(['RT_USING_USB_DEVICE']):
    src += ['drv_usbd.c']

if GetDepend(['RT_USING_SPI_WIFI']):
    src += ['drv_rw00x.c']

if GetDepend(['BSP_USING_QSPI_FLASH']):
    src += ['drv_qspi.c', 'stm32469i_discovery_qspi.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = inc)

Return('group')