Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = os.path.join(str(Dir('#')), 'drivers')

# add the general drivers.
src = Split("""
board.c
stm32f4xx_it.c
drv_usart.c
drv_romfs.c
""")

if GetDepend(['RT_USING_PIN']):
    src += ['drv_gpio.c']

if GetDepend(['BSP_USING_I2C2']):
	src += ['drv_i2c.c']

if GetDepend(['BSP_USING_SPI']):
    src += ['drv_spi.c']

if GetDepend(['BSP_USING_SDRAM']):
    src += ['drv_sdram.c']

if GetDepend(['BSP_USING_SDCARD']):
    src += ['drv_sdcard.c']

if GetDepend(['BSP_USING_AUDIO']):
    src += ['drv_audio.c']

if GetDepend(['BSP_USING_LCD']):
    src += ['drv_lcd.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = [cwd])

Return('group')

